services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - .:/app
      - sqlite_data:/app/storage
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: alpine:latest
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null"
    volumes:
      - sqlite_data:/data
    networks:
      - app-network

volumes:
  sqlite_data:
    driver: local

networks:
  app-network:
    driver: bridge
