version: "3.8"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - .:/app  # Mapeando a pasta atual para a pasta /app no container
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: localhost
      DATABASE_USERNAME: sqlite
      DATABASE_PASSWORD: sqlite
      DATABASE_NAME: storage/development.sqlite3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
